include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # We do not require to document all public members, since we do not develop an SDK
    public_member_api_docs: false
    # Turned off so that we can keep comments and strings that are longer
    lines_longer_than_80_chars: false
    # As a team decision we keep this rule disabled
    avoid_positional_boolean_parameters: false
    avoid_setters_without_getters: false
    always_put_required_named_parameters_first: false

analyzer:
  exclude:
    - build/**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/gen/openapi/**
    - lib/firebase_options_**.dart
  plugins:
    - custom_lint
