name: gunslinger_rush
description: "Gunslinger Rush"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.3
  json_annotation: ^4.8.1
  logger: ^2.2.0
  ntp: ^2.0.0
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  dart_style: ^2.3.6
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Carnevalee
      fonts:
        - asset: assets/fonts/Carnevalee-Freakshow.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
